# Changes here will be overwritten by Copier
_commit: 1.5.7
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2023'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: false
project_description: Output API docs to Markdown using Griffe.
project_name: griffe2md
python_package_command_line_name: griffe2md
python_package_distribution_name: griffe2md
python_package_import_name: griffe2md
repository_name: griffe2md
repository_namespace: mkdocstrings
repository_provider: github.com

